skip_commits:
  files:
    - '**/*.md'
    - '.vscode/**/*'
cache:
  - '%USERPROFILE%\Documents\WindowsPowerShell\Modules -> .appveyor.yml'
matrix:
  fast_finish: true
build: 'off'
image: Visual Studio 2019
environment:
  SCOOP: C:\projects\scoop
  SCOOP_HOME: C:\projects\scoop\apps\scoop\current
  matrix:
    - PowerShell: 5
    - PowerShell: 6
init:
  - ps: |
      (Get-PSProvider 'FileSystem').Home = 'C:\projects\'
      if(!(Test-Path "$env:SCOOP_HOME")) { git clone -q --depth=1 "https://github.com/lukesampson/scoop" "$env:SCOOP_HOME" }
for:
  - matrix:
      only:
        - PowerShell: 5
    install:
      - ps: . "$env:SCOOP_HOME\test\bin\init.ps1"
    test_script:
      - ps: . "$env:SCOOP_HOME\test\bin\test.ps1" -TestPath "$env:APPVEYOR_BUILD_FOLDER"
  - matrix:
      only:
        - PowerShell: 6
    install:
      - pwsh: . "$env:SCOOP_HOME\test\bin\init.ps1"
    test_script:
      - pwsh: . "$env:SCOOP_HOME\test\bin\test.ps1" -TestPath "$env:APPVEYOR_BUILD_FOLDER"
